package org.akuunda.akuundawallet.wallet.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GenereLinkResponse {

    /** Transaction ID (sequenceId) generated by akuundapay_generelinkYC, e.g. AKU_CI_1710439793000 */
    private String transactionId;

    /** Full payment URL for the client, e.g. https://link.akuunda-pay.io/payment.html?transaction=AKU_CI_xxx */
    private String paymentUrl;
}
